/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExhibitLayoutRouteImport } from './routes/exhibit/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExhibitSlugRouteImport } from './routes/exhibit/$slug'

const ExhibitLayoutRoute = ExhibitLayoutRouteImport.update({
  id: '/exhibit',
  path: '/exhibit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitSlugRoute = ExhibitSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExhibitLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exhibit': typeof ExhibitLayoutRouteWithChildren
  '/exhibit/$slug': typeof ExhibitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exhibit': typeof ExhibitLayoutRouteWithChildren
  '/exhibit/$slug': typeof ExhibitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exhibit': typeof ExhibitLayoutRouteWithChildren
  '/exhibit/$slug': typeof ExhibitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exhibit' | '/exhibit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exhibit' | '/exhibit/$slug'
  id: '__root__' | '/' | '/exhibit' | '/exhibit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExhibitLayoutRoute: typeof ExhibitLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exhibit': {
      id: '/exhibit'
      path: '/exhibit'
      fullPath: '/exhibit'
      preLoaderRoute: typeof ExhibitLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibit/$slug': {
      id: '/exhibit/$slug'
      path: '/$slug'
      fullPath: '/exhibit/$slug'
      preLoaderRoute: typeof ExhibitSlugRouteImport
      parentRoute: typeof ExhibitLayoutRoute
    }
  }
}

interface ExhibitLayoutRouteChildren {
  ExhibitSlugRoute: typeof ExhibitSlugRoute
}

const ExhibitLayoutRouteChildren: ExhibitLayoutRouteChildren = {
  ExhibitSlugRoute: ExhibitSlugRoute,
}

const ExhibitLayoutRouteWithChildren = ExhibitLayoutRoute._addFileChildren(
  ExhibitLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExhibitLayoutRoute: ExhibitLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
